### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ihodes** [pulseio/impala-base64#1]
Preferably Apache 2.0 :)

**Comment by beeandbo** [comment]
We recently went through an acquisition, so I need to get some guidance on this.  Will get back to you asap on adding a license.  I agree, I'd like to use Apache :)

**Comment by k9delight** [comment]
If you need guidance on suitable licenses, go/opensource on the corp
network will be more than happy to assist you with licensing choices (even
if not related to opensource projects).

**Comment by ihodes** [comment]
@tzeskimo Thanks so much, and congratulations on the acquisition!
